# import the OpenAI Python library for calling the OpenAI API
from openai import OpenAI
import os

client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY", "<your OpenAI API key if not set as env var>"))

# Example OpenAI Python library request
MODEL = "gpt-3.5-turbo"

# Get user input for the user message
user_message = input("Please enter your message: ")

# Make a request to the OpenAI API using the user's input as the user message
response = client.chat.completions.create(
    model=MODEL,
    # Use user's input as the user message
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": user_message},
    ],
    temperature=0,
)

# Print the response generated by the AI
print(response.choices[0].message.content)